### ISSUE TITLE
Error al subir xml y crear productos

### ISSUE THREAD

**Issue by celm1990** [dansanti/l10n_cl_dte#7]
Cuando intento subir el xml de un proveedor y el producto no existe en el sistema, se trata de crear el producto pero sale el siguiente error:

![screenshot_1](https://cloud.githubusercontent.com/assets/7775116/21697649/545da220-d361-11e6-9422-826a88e5ee11.png)

El problema es que al crear el producto no se especifica la categoria, esto en la linea [465](https://github.com/dansanti/l10n_cl_dte/blob/9.0/wizard/upload_xml.py#L465), deberiamos en el asistente preguntar la categoria para los nuevos productos, o configurarla en algun lado(compañia) o crearla dinamicamente segun el proveedor.

**Comment by dansanti** [comment]
Voy a mirar cómo lo hace odoo para seleccionar una categoría por defecto,
no me había dado cuenta de ese detalle.

El 05/01/2017 18:11, "Carlos Lopez" <notifications@github.com> escribió:

Cuando intento subir el xml de un proveedor y el producto no existe en el
sistema, se trata de crear el producto pero sale el siguiente error:

[image: screenshot_1]
<https://cloud.githubusercontent.com/assets/7775116/21697649/545da220-d361-11e6-9422-826a88e5ee11.png>

El problema es que al crear el producto no se especifica la categoria, esto
en la linea 465
<https://github.com/dansanti/l10n_cl_dte/blob/9.0/wizard/upload_xml.py#L465>,
deberiamos en el asistente preguntar la categoria para los nuevos
productos, o configurarla en algun lado(compañia) o crearla dinamicamente
segun el proveedor.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/dansanti/l10n_cl_dte/issues/7>, or mute the thread
